#!/bin/bash
# ceph-health-cron
#
# Reports the health of a ceph cluster.
# Should be run hourly on all your ceph mons; but at most one
# will email you each hour.
#
# Contributors:
#    Dan van der Ster (daniel.vanderster@cern.ch)
#    Matthias Schoenberg (kontakt@ms-itd.de)
#
# Usage:
# ./ceph-health-cron <# mons> <mon id, starting with 0>
#
# Example:
# ./ceph-health-cron 5 <0|1|2|3|4>

if [[ $# -lt 2 ]]
then
    echo "Usage: $0 <# monitors> <this mon id>"
    exit 0
fi

# rotate through the mons whose turn it is to run the health script
NMONS=$1
ID=$2
ROTA=$(( $( date +%k ) % $NMONS ))
if [ "$ID" != "$ROTA" ]
then
    exit
fi

# check ceph health
HEALTH=$(timeout 30 ceph health)
if [ "$?" = 124 ] #timeout's exit code is 124 when the timeout is hit
then
    HEALTH="ceph health timed out (30s), potential loss of quorum!" #using $HEALTH since it wouldn't get initialized when it times out
fi

if [ "$HEALTH" != 'HEALTH_OK' ]
then
    echo -n "Ceph is not healthy: "
    echo "$HEALTH"
    echo
fi

# get logs for last hour
rm -f /tmp/ceph.log.lasthour
awk -vTIME=`date -d'now-1 hours' +%H:%M:%S` ' { if ($2 > TIME) print $0}' /var/log/ceph/ceph.log >> /tmp/ceph.log.lasthour

# check for WRN or DBG log messages in the past hour
WARNINGS=$(grep -v INF /tmp/ceph.log.lasthour)
if [ "$WARNINGS" ]
then
    echo -n "Warnings in ceph.log: "
    echo "$WARNINGS"|wc -l
    echo
fi

# check for down osd's
DOWNOSD=$(egrep 'out|down|fail|boot' /tmp/ceph.log.lasthour | grep -v pgmap)
if [ "$DOWNOSD" ]
then
    echo Out/Down/Failed/Booted OSDs:
    echo "$DOWNOSD"
    echo
fi

# check for slow requests
SLOW=$(grep slow /tmp/ceph.log.lasthour | grep oldest)
if [ "$SLOW" ]
then
    echo Slow Requests:
    echo "$SLOW"
    echo
fi

# check for monitor elections
ELEC=$(grep election /tmp/ceph.log.lasthour)
if [ "$ELEC" ]
then
    echo Monitor Elections:
    echo "$ELEC"
    echo
fi
