#!/usr/bin/env python

from collections import defaultdict
from cephinfo import cephinfo
import sys

all = False
if len(sys.argv) > 1:
    pool = sys.argv[1]
    if pool == 'all':
        all = True
    else:
        pools = pool.split(',')
        for pool in pools:
            try:
                int(pool)
            except ValueError:
                print("Parameter %s does not look like a pool id." % pool)
                sys.exit(1)
else:
    print("Usage: ceph-pool-pg-distribution <pool id>[,<pool id>]")
    sys.exit(1)

print("Searching for PGs in pools: {0}".format(pools))
cephinfo.init_pg()
osds_d = defaultdict(int)
total_pgs = 0

for pg in cephinfo.get_pg_stats():
    poolnum = pg['pgid'].split('.')[0]
    if not all and poolnum not in pools:
        continue
    total_pgs += 1
    for osd in pg['up']:
        osds_d[osd] += 1

total_osds = len(osds_d.keys())

print("Summary: {0} PGs on {1} osds\n".format(total_pgs, total_osds))
print("Num OSDs with X PGs:")

count_d = defaultdict(int)
for value in osds_d.values():
    count_d[value] += 1

for k, v in sorted(count_d.items()):
    print("{0}: {1}".format(k, v))
