#!/usr/bin/env python2

import json, subprocess, multiprocessing

def pfunc(osd_id):
    subprocess.check_output(['ceph-volume', 'lvm', 'activate', osd_id, jj[osd_id][0]['tags']['ceph.osd_fsid']])
	

if __name__ == "__main__":
    print "Detecting drives..."
    JSON = subprocess.check_output(['ceph-volume', 'lvm', 'list', '--format=json'])

    jj = json.loads(JSON)

    cpu_num = multiprocessing.cpu_count()
    p = multiprocessing.Pool(cpu_num)

    print "Activating osds..."
    p.map(pfunc, jj.keys())
    print "Done" 
