#!/bin/bash

echo "This script will ERASE this host's osds from the cluster" \
     "and make new ones with the bluestore format"
read -p "Are you sure you want to proceed? (y/n): " -r

case $REPLY in
  y ) echo "Starting osd removal operation.";;
  * ) echo "Exiting..."; exit 0;;
esac

disks=($(ceph-disk list | grep 'ceph data' | awk '{ print substr($1, 0, length($1)-1) }'))
osds=($(ceph-disk list | grep -oP '(?<=osd\.)[0-9]+'))

for i in ${!osds[@]};
do
  if [[ ceph osd metadata ${osds[i]} | grep -P '"osd_objectstore":\s*"filestore"' ]]
  then
    echo ceph osd out ${osds[i]}
    echo while ! ceph osd safe-to-destroy ${osds[i]} ; sleep 10 ; done
    echo systemctl kill ceph-osd@${osds[i]}

    if [[ mount | grep -P "/var/lib/ceph/osd/ceph-${osds[i]}\b" ]]
    then
      echo unmount /var/lib/ceph/osd/ceph-${osds[i]}
    fi

    echo ceph osd destroy ${osds[i]} --yes-i-really-mean-it
    echo ceph-volume lvm zap ${disks[i]}
    echo ceph-volume lvm create --bluestore --osd-id ${osds[i]} --data ${disks[i]}
  fi
done
